### ISSUE TITLE
Is our decision to use a non-production ready version of the app?

### ISSUE THREAD

**Issue by mtliendo** [qccoders/qccoders.org#29]
The page isn't optimized for production at the moment.  Not really a bug, since our org may want others to see how we structure our code in the dev tools.  Obviously there's performance reasons to set the `env` to`production` but maybe something to discuss.

**Comment by jpdillingham** [comment]
I would definitely support deployment of webpack-ed artifacts to the production instance.  We can link back to staging for the curious.

Any suggestions on how webpack could be integrated into the current pipeline?  A cursory review  suggests that Travis supports webpack, we'd just have to figure out which knobs to twiddle in .travis.yml.

**Comment by model3volution** [comment]
In some of the pipelines we have in place at work we have our pull requests trigger a  new build.  When the new build is triggered, it starts by running the command `webpack -p`.  The trick is that since webpack isn't a global module, it has to be accessed locally. This is trivial if we add a new build script:

`package.json`

`scripts: {`
`build-prod: "webpack -p" `
`}`

This will create a new optimized build (though I'll have to check on the specifics) then instead of serving our normal build to github, we can serve the prod version.

**Comment by jpdillingham** [comment]
Need to tweak `travis.yml` to build: 

```yaml
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
```

Getting it to deploy the build artifacts will take a little reading.  I'll close this issue and create another.
